name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 1. Configura o Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 2. Configura o Java (Necessário para o Android)
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Instala as dependências
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install flet

    # 4. Constrói o APK forçando o "Sim" (yes)
    # O comando "yes" responde "y" automaticamente para a pergunta do Flet
    - name: Flet Build APK
      run: |
        yes | flet build apk --verbose

    # 5. Faz o upload do arquivo gerado
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: player_pro_v3.apk
        path: build/apk/app-release.apk
